name: Build the Docs

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  container-job:
    runs-on: ubuntu-latest

    container:
      image: f5devcentral/containthedocs:latest

    steps:
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install awscli --upgrade
        pip install sphinx-copybutton
        if [ -f ./requirements.txt ]; then pip install -r ./requirements.txt; fi
    - name: Build the Docs
      run: |
        ./scripts/docker-docs.sh ./scripts/test-docs.sh
