name: Build the Docs
on: [push]
jobs:
  container-job:
    runs-on: ubuntu-latest

    container:
      image: f5devcentral/containthedocs:latest

    steps:
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install awscli --upgrade
        pip install sphinx-copybutton
        pip install sphinx-autobuild
        if [ -f ./requirements.txt ]; then pip install -r ./requirements.txt; fi
    - name: Build the Docs
      run: |
        make -C docs clean
        make -C docs html
