name: Build the Docs
on:
  push:
    branches:
      - master
      - dev
jobs:
  build-the-docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2.2.1

    - name: Branch Name
      run: |
        echo "Running on branch> ${GITHUB_REF##*/}"

    - name: Prepare the Environment
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Build the Docs
      run: |
        ./containthedocs-build.sh

    - name: Copy versions.json
      run: |
        sudo cp $PWD/versions.json $PWD/docs/_build/
