name: Sphinx Build

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  container-job:
    runs-on: ubuntu-latest

    container:
      image: f5devcentral/containthedocs:latest

    steps:
    - name: Sphinx Build
      # You may pin to the exact commit or the version.
      # uses: ammaraskar/sphinx-action@8b4f60114d7fd1faeba1a712269168508d4750d2
      uses: ammaraskar/sphinx-action@0.4
      with:
        # The folder containing your sphinx docs.
        docs-folder: docs/
        # The command used to build your documentation.
        build-command: make html
        # Run before the build command, you can use this to install system level dependencies, for example with "apt-get update -y && apt-get install -y perl"
        pre-build-command: python -m pip install --upgrade pip