name: Sphinx Build
on: [push]
jobs:
  build-the-docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: "docs/"
        pre-build-command: "python -m pip install --upgrade pip && pip install -r ./requirements.txt"
        build-command: "sphinx-build -b html . _build"
